// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/proto.proto

package grpcPb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogRequest_Actions int32

const (
	LogRequest_SignUp       LogRequest_Actions = 0
	LogRequest_SignIn       LogRequest_Actions = 1
	LogRequest_Logout       LogRequest_Actions = 2
	LogRequest_Upload       LogRequest_Actions = 3
	LogRequest_Get_files    LogRequest_Actions = 4
	LogRequest_Get_file     LogRequest_Actions = 5
	LogRequest_Delete_file  LogRequest_Actions = 6
	LogRequest_Delete_files LogRequest_Actions = 7
)

// Enum value maps for LogRequest_Actions.
var (
	LogRequest_Actions_name = map[int32]string{
		0: "SignUp",
		1: "SignIn",
		2: "Logout",
		3: "Upload",
		4: "Get_files",
		5: "Get_file",
		6: "Delete_file",
		7: "Delete_files",
	}
	LogRequest_Actions_value = map[string]int32{
		"SignUp":       0,
		"SignIn":       1,
		"Logout":       2,
		"Upload":       3,
		"Get_files":    4,
		"Get_file":     5,
		"Delete_file":  6,
		"Delete_files": 7,
	}
)

func (x LogRequest_Actions) Enum() *LogRequest_Actions {
	p := new(LogRequest_Actions)
	*p = x
	return p
}

func (x LogRequest_Actions) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogRequest_Actions) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_proto_proto_enumTypes[0].Descriptor()
}

func (LogRequest_Actions) Type() protoreflect.EnumType {
	return &file_proto_proto_proto_enumTypes[0]
}

func (x LogRequest_Actions) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogRequest_Actions.Descriptor instead.
func (LogRequest_Actions) EnumDescriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{0, 0}
}

type LogRequest_Methods int32

const (
	LogRequest_GET    LogRequest_Methods = 0
	LogRequest_PUT    LogRequest_Methods = 1
	LogRequest_POST   LogRequest_Methods = 2
	LogRequest_DELETE LogRequest_Methods = 3
)

// Enum value maps for LogRequest_Methods.
var (
	LogRequest_Methods_name = map[int32]string{
		0: "GET",
		1: "PUT",
		2: "POST",
		3: "DELETE",
	}
	LogRequest_Methods_value = map[string]int32{
		"GET":    0,
		"PUT":    1,
		"POST":   2,
		"DELETE": 3,
	}
)

func (x LogRequest_Methods) Enum() *LogRequest_Methods {
	p := new(LogRequest_Methods)
	*p = x
	return p
}

func (x LogRequest_Methods) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogRequest_Methods) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_proto_proto_enumTypes[1].Descriptor()
}

func (LogRequest_Methods) Type() protoreflect.EnumType {
	return &file_proto_proto_proto_enumTypes[1]
}

func (x LogRequest_Methods) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogRequest_Methods.Descriptor instead.
func (LogRequest_Methods) EnumDescriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{0, 1}
}

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        LogRequest_Actions     `protobuf:"varint,1,opt,name=action,proto3,enum=grpcPb.LogRequest_Actions" json:"action,omitempty"`
	Method        LogRequest_Methods     `protobuf:"varint,2,opt,name=method,proto3,enum=grpcPb.LogRequest_Methods" json:"method,omitempty"`
	UserId        int32                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	ObjectId      []string               `protobuf:"bytes,4,rep,name=objectId,proto3" json:"objectId,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_proto_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{0}
}

func (x *LogRequest) GetAction() LogRequest_Actions {
	if x != nil {
		return x.Action
	}
	return LogRequest_SignUp
}

func (x *LogRequest) GetMethod() LogRequest_Methods {
	if x != nil {
		return x.Method
	}
	return LogRequest_GET
}

func (x *LogRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LogRequest) GetObjectId() []string {
	if x != nil {
		return x.ObjectId
	}
	return nil
}

func (x *LogRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *LogRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type LogResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponce) Reset() {
	*x = LogResponce{}
	mi := &file_proto_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponce) ProtoMessage() {}

func (x *LogResponce) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponce.ProtoReflect.Descriptor instead.
func (*LogResponce) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{1}
}

func (x *LogResponce) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type GinLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Latency       string                 `protobuf:"bytes,3,opt,name=latency,proto3" json:"latency,omitempty"`
	ClientIp      string                 `protobuf:"bytes,4,opt,name=clientIp,proto3" json:"clientIp,omitempty"`
	Method        string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	UserAgent     string                 `protobuf:"bytes,7,opt,name=userAgent,proto3" json:"userAgent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GinLogRequest) Reset() {
	*x = GinLogRequest{}
	mi := &file_proto_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GinLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GinLogRequest) ProtoMessage() {}

func (x *GinLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GinLogRequest.ProtoReflect.Descriptor instead.
func (*GinLogRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{2}
}

func (x *GinLogRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GinLogRequest) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GinLogRequest) GetLatency() string {
	if x != nil {
		return x.Latency
	}
	return ""
}

func (x *GinLogRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *GinLogRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *GinLogRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GinLogRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type GinLogResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GinLogResponce) Reset() {
	*x = GinLogResponce{}
	mi := &file_proto_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GinLogResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GinLogResponce) ProtoMessage() {}

func (x *GinLogResponce) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GinLogResponce.ProtoReflect.Descriptor instead.
func (*GinLogResponce) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{3}
}

func (x *GinLogResponce) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_proto_proto_proto protoreflect.FileDescriptor

const file_proto_proto_proto_rawDesc = "" +
	"\n" +
	"\x11proto/proto.proto\x12\x06grpcPb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa2\x03\n" +
	"\n" +
	"LogRequest\x122\n" +
	"\x06action\x18\x01 \x01(\x0e2\x1a.grpcPb.LogRequest.ActionsR\x06action\x122\n" +
	"\x06method\x18\x02 \x01(\x0e2\x1a.grpcPb.LogRequest.MethodsR\x06method\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x05R\x06userId\x12\x1a\n" +
	"\bobjectId\x18\x04 \x03(\tR\bobjectId\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"y\n" +
	"\aActions\x12\n" +
	"\n" +
	"\x06SignUp\x10\x00\x12\n" +
	"\n" +
	"\x06SignIn\x10\x01\x12\n" +
	"\n" +
	"\x06Logout\x10\x02\x12\n" +
	"\n" +
	"\x06Upload\x10\x03\x12\r\n" +
	"\tGet_files\x10\x04\x12\f\n" +
	"\bGet_file\x10\x05\x12\x0f\n" +
	"\vDelete_file\x10\x06\x12\x10\n" +
	"\fDelete_files\x10\a\"1\n" +
	"\aMethods\x12\a\n" +
	"\x03GET\x10\x00\x12\a\n" +
	"\x03PUT\x10\x01\x12\b\n" +
	"\x04POST\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03\"%\n" +
	"\vLogResponce\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"\xe9\x01\n" +
	"\rGinLogRequest\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x02 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\alatency\x18\x03 \x01(\tR\alatency\x12\x1a\n" +
	"\bclientIp\x18\x04 \x01(\tR\bclientIp\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12\x1c\n" +
	"\tuserAgent\x18\a \x01(\tR\tuserAgent\"(\n" +
	"\x0eGinLogResponce\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status2u\n" +
	"\n" +
	"LogService\x12.\n" +
	"\x03Log\x12\x12.grpcPb.LogRequest\x1a\x13.grpcPb.LogResponce\x127\n" +
	"\x06GinLog\x12\x15.grpcPb.GinLogRequest\x1a\x16.grpcPb.GinLogResponceB\rZ\v/pkg/grpcPbb\x06proto3"

var (
	file_proto_proto_proto_rawDescOnce sync.Once
	file_proto_proto_proto_rawDescData []byte
)

func file_proto_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_proto_rawDesc), len(file_proto_proto_proto_rawDesc)))
	})
	return file_proto_proto_proto_rawDescData
}

var file_proto_proto_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_proto_proto_goTypes = []any{
	(LogRequest_Actions)(0),       // 0: grpcPb.LogRequest.Actions
	(LogRequest_Methods)(0),       // 1: grpcPb.LogRequest.Methods
	(*LogRequest)(nil),            // 2: grpcPb.LogRequest
	(*LogResponce)(nil),           // 3: grpcPb.LogResponce
	(*GinLogRequest)(nil),         // 4: grpcPb.GinLogRequest
	(*GinLogResponce)(nil),        // 5: grpcPb.GinLogResponce
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_proto_proto_proto_depIdxs = []int32{
	0, // 0: grpcPb.LogRequest.action:type_name -> grpcPb.LogRequest.Actions
	1, // 1: grpcPb.LogRequest.method:type_name -> grpcPb.LogRequest.Methods
	6, // 2: grpcPb.LogRequest.timestamp:type_name -> google.protobuf.Timestamp
	6, // 3: grpcPb.GinLogRequest.timestamp:type_name -> google.protobuf.Timestamp
	2, // 4: grpcPb.LogService.Log:input_type -> grpcPb.LogRequest
	4, // 5: grpcPb.LogService.GinLog:input_type -> grpcPb.GinLogRequest
	3, // 6: grpcPb.LogService.Log:output_type -> grpcPb.LogResponce
	5, // 7: grpcPb.LogService.GinLog:output_type -> grpcPb.GinLogResponce
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_proto_proto_init() }
func file_proto_proto_proto_init() {
	if File_proto_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_proto_rawDesc), len(file_proto_proto_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_proto_depIdxs,
		EnumInfos:         file_proto_proto_proto_enumTypes,
		MessageInfos:      file_proto_proto_proto_msgTypes,
	}.Build()
	File_proto_proto_proto = out.File
	file_proto_proto_proto_goTypes = nil
	file_proto_proto_proto_depIdxs = nil
}
